# Generated by Django 4.1.1 on 2022-09-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_company_contact_transport_contact_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
