# Generated by Django 4.1.1 on 2022-09-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
