# Generated by Django 4.1.1 on 2022-09-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_activity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='package',
        ),
        migrations.CreateModel(
            name='PackageAccomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.accomodation')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.package')),
            ],
        ),
    ]
