# Generated by Django 4.1.1 on 2022-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_accomodation_package_packageaccomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
