# Generated by Django 4.1.1 on 2022-09-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_accomodation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ImageField(default=9, upload_to='pics'),
            preserve_default=False,
        ),
    ]
