# Generated by Django 4.1.1 on 2022-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mission',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
